<?php
    
	include_once("lib/mgoos_config.php") ;
    include_once("lib/session_manager.php");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<TITLE> Terms of Service </TITLE>
		<link rel="stylesheet" type="text/css" href="./css/mgoos.css" />
		<META NAME="Generator" CONTENT="EditPlus">
		<META NAME="Author" CONTENT="">
		<META NAME="Keywords" CONTENT="">
		<META NAME="Description" CONTENT="">
	</HEAD>
	
	<BODY>
		<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
			<TR ALIGN="CENTER">
				<!-- Header -->
				<?php				include_once(CMGooSConfig::MGOOS_ROOT."/lib/header.php?folder_level=0&page_id=".CMGooSConfig::HF_TOS_ID."&login=".CSessionManager::IsLoggedIn());
				?>
			</TR>
			<TR>
				<TD>
					<p align="center"><A HREF="http://localhost/mgoos/index.php"><IMG SRC="images/mgoos_thumbnail.png" WIDTH="123" HEIGHT="61" BORDER="0" ALT=""/></A></p>
					<p class="indented"><p class="heading">Terms of Service</p>
The following Terms of Service (ToS) given by <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> , as it is a legal document.</BR>

<p class="heading">Prohibitions</p>
1.	collect or modify any <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> user account information;</BR></BR>
2.	interfere or attempt to interfere in any manner with the proper workings of the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> that adversely affects the functionality or performance of <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> or services provided     by <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>;</BR></BR>
3.	circumvent or render ineffective any geographical restrictions, including IP			address-based restrictions;</BR></BR>
4.	modify or replace the text, images, audio or other content of the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> search			results, including (i) changing the order in which search results are presented as		<A class='anchor' HREF="http://www.mgoos.com">MGooS</A> search results, or (ii) intermixing sources other than <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>  when search			results are presented as <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>  search results;</BR></BR>
5.	modify, replace or otherwise disable the functioning of links to <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> or third-party		websites provided in the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> search results or otherwise provided through the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>		player;</BR></BR>
6.	separate, isolate, or modify the audio or video components of any <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> ;</BR></BR> 
7.	promote separately the audio or video components of any <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> ;</BR></BR>
8.	access any portion of any <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> audio content by any means other than use of a <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>		player;</BR></BR>
9.	store copies of <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> audio or audiovisual content;</BR></BR>
10.	use the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> intentionally to encourage or promote copyright infringement or the		exploitation of copyright-infringing materials;</BR></BR>
11.	misrepresent your identity when registering for use of the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> , use the developer		credentials licensed to a different individual or entity;</BR></BR>
12.	use a audio/video player smaller than the minimum audio/video player size set forth		in the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> documentation and specifications.</BR>
	<p class="heading">Additional Legal Provisions</p>
1.	<span class="boldfont">Compliance with Laws.</span> You are responsible for complying with all applicable laws,        rules and regulations, all third-party rights and all <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> policies. You shall not		use the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> site in a manner that violates such laws, rules and regulations, third		parties' rights or any <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> policies or in a manner that is deceptive, unethical,		false or misleading. For avoidance of doubt, You shall not distribute or provide		access to applications you develop in contravention of India export control or trade		laws.</BR></BR>
2.	<span class="boldfont">No Implied Rights.</span> Except as expressly granted herein, neither party through this		Agreement grants the other party any intellectual property rights or other propriety		rights. As between You and <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> , its corporate affiliates, and its applicable			licensors retain all intellectual property rights (including all patent, trademark,		copyright, trade secret, and other proprietary rights) in and to the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> documentation and specifications. All license rights granted herein are not				sublicensable, transferable or assignable unless otherwise stated herein.</BR></BR>
3.	<span class="boldfont">Non-exclusive.</span> This Agreement is a non-exclusive agreement. You acknowledge that		<A class='anchor' HREF="http://www.mgoos.com">MGooS</A> may be developing and may develop products or services that may compete with		this <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> player, or any other products or services.</BR></BR>
4.	<span class="boldfont">Publicity.</span> You agree that <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> may use Your company, organization, or product name		and/or logo in presentations, marketing materials, customer lists, financial reports,		website listings of customers, research and marketing case studies and other			marketing-related activities. You may not issue any public announcement regarding		Your use of the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>.</BR></BR>
5.	<span class="boldfont">Indemnification.</span> You shall indemnify, defend and hold <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> , affiliates, and			harmless from any claim, costs, losses, damages, liabilities, judgments and expenses		(including reasonable fees of attorneys and other professionals), arising out of or		in connection with any claim, action or proceeding (any and all of which are			"Claims") by a third party arising out of Your use of the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> in any manner that		breaches this Agreement or otherwise arising out of materials or technology				contributed by You and not by <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>. At <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> option, You shall assume control of the		defense and settlement of any Claim subject to indemnification by You (provided that,		in such event, <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> may at any time thereafter elect to take over control of the		defense and settlement of any such Claim, and in any event, You shall not settle any		such Claim without <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> prior written consent).</BR></BR>
6.	<span class="boldfont">Termination.</span> Any licenses contained in this Agreement will terminate automatically		without notice if You fail to comply with any provision of this Agreement.<A class='anchor' HREF="http://www.mgoos.com">MGooS</A>		reserves the right to terminate this Agreement or discontinue the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> or any			portion or feature thereof for any or no reason and at any time without liability to		You. Upon any termination or notice of any discontinuance, You shall immediately stop		and thereafter desist from using the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> web application and delete all <A class='anchor' HREF="http://www.mgoos.com">MGooS<A/> Data		in Your possession or control (including, without limitation, from Your servers).		Section III of this Agreement shall survive any termination or expiration of this		Agreement and will continue to bind You in accordance with its terms.</BR></BR>
7.	<span class="boldfont">Modification.</span> <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> may modify any of the terms and conditions contained in this		Agreement at any time and in its sole discretion by posting a change notice to Your		account, changing these terms and conditions, emailing to the email address of Your		account or account associated with Your developer credentials or otherwise notifying		You. IF ANY MODIFICATION IS UNACCEPTABLE TO YOU, YOUR ONLY RECOURSE IS TO TERMINATE		THIS AGREEMENT. YOUR CONTINUED USE OF THE <A class='anchor' HREF="http://www.mgoos.com">MGOOS</A> API, CONTINUED POSSESSION OF A COPY		OF NON-PUBLIC <A class='anchor' HREF="http://www.mgoos.com">MGOOS</A> API DOCUMENTATION AND SPECIFICATIONS OR CONTINUED DEVELOPMENT		FOLLOWING POSTING OF A CHANGE NOTICE OR NEW AGREEMENT ON OUR SITE WILL CONSTITUTE		BINDING ACCEPTANCE OF THE CHANGE.</BR></BR>
8.	<span class="boldfont">Release.</span> You hereby release and covenant not to sue <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> and its corporate				affiliates and any of their officers, directors, employees, agents, shareholders,		licensors, licensees, assigns or successors, for any and all damages, liabilities,		causes of action, judgments, and claims (a) pertaining to any intellectual property		You develop that is based on, uses, or relates to the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> ; and (b) which otherwise		may arise in connection with Your use of, reliance on, or reference to the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A>. If		You have a dispute with one or more <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> account owners, You release <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> and its		corporate affiliates and any of their , directors, employees, shareholders,				licensors, licensees, assigns or successors, for any and all damages, liabilities,		causes of action, judgments, and claims arising out of or in any way connected with		such disputes. If You are a Madhya Pradesh resident, You waive India Civil Code 1908		which says: "A general release does not extend to claims which the creditor does not		know or suspect to exist in his favor at the time of executing the release, which if		known by him must have materially affected his settlement with the debtor."</BR></BR>
9.	<span class="boldfont">Miscellaneous.</span> The Agreement is governed by India law, except for Madhya Pradesh		conflicts of laws principles, and all claims arising out of or relating to this			Agreement or the <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> services and programs shall be litigated exclusively in			the federal or state courts of Madhya Pradesh, India and You and <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> consent to		personal jurisdiction in those courts. The Agreement constitutes the entire agreement		between the parties with respect to the subject matter hereof. You may grant			approvals, permissions and consents to <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> by email, but any modifications by You		to this Agreement shall be made in a writing (not including email) executed by both		parties. Any notices to <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> shall be sent to our corporate headquarters address as		set forth on our website via first class or air mail or overnight courier, and is		deemed given upon receipt. A waiver of any default is not a waiver of any subsequent		default. Unenforceable provisions will be modified to reflect the parties' intention,		and remaining provisions of the Agreement will remain in full effect. You shall not		assign or otherwise transfer any of Your rights or delegate Your obligations			hereunder and any such attempt is null and void. You and <A class='anchor' HREF="http://www.mgoos.com">MGooS</A> are not legal partners		or agents, but are independent contractors.</p></BR></BR>
				</TD>
			</TR>
			<TR>
				<?php								include_once(CMGooSConfig::MGOOS_ROOT."/lib/footer.php?folder_level=0&page_id=".CMGooSConfig::HF_TOS_ID."&login=".CSessionManager::IsLoggedIn()); 
				?>
			</TR>
		</TABLE>
 </BODY>
</HTML>